"""Adicionar campos last_login, created_at e updated_at ao modelo User

Revision ID: 06ae44016383
Revises: 2595ffa5342e
Create Date: 2025-06-24 09:55:31.670269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06ae44016383'
down_revision = '2595ffa5342e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formulario_gerado')
    with op.batch_alter_table('peticao_placeholders', schema=None) as batch_op:
        batch_op.alter_column('obrigatorio',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('users_peticionador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_peticionador', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_login')

    with op.batch_alter_table('peticao_placeholders', schema=None) as batch_op:
        batch_op.alter_column('obrigatorio',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    op.create_table('formulario_gerado',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modelo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dados_preenchidos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_geracao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_envio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_peticionador.id'], name=op.f('fk_formulario_gerado_cliente_id_clientes_peticionador')),
    sa.ForeignKeyConstraint(['modelo_id'], ['peticao_modelos.id'], name=op.f('fk_formulario_gerado_modelo_id_peticao_modelos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formulario_gerado'))
    )
    # ### end Alembic commands ###
