"""Altera coluna observacoes_processamento para Text

Revision ID: 0b673a3309d3
Revises:
Create Date: 2025-06-22 16:02:35.101055

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0b673a3309d3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("respostas_form", schema=None) as batch_op:
        batch_op.alter_column(
            "observacoes_processamento",
            existing_type=sa.VARCHAR(length=256),
            type_=sa.Text(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("respostas_form", schema=None) as batch_op:
        batch_op.alter_column(
            "observacoes_processamento",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=256),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
