"""add persona analysis system and formulario placeholders

Revision ID: af01c0adb1f5
Revises: 06ae44016383
Create Date: 2025-06-24 11:53:10.565152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af01c0adb1f5'
down_revision = '06ae44016383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulario_placeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=128), nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('tipo_campo', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('placeholder_text', sa.String(length=200), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('opcoes_json', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['peticao_modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_analises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.String(length=64), nullable=False),
    sa.Column('personas_detectadas', sa.JSON(), nullable=True),
    sa.Column('patterns_detectados', sa.JSON(), nullable=True),
    sa.Column('total_placeholders', sa.Integer(), nullable=True),
    sa.Column('total_personas', sa.Integer(), nullable=True),
    sa.Column('sugestoes', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['peticao_modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('peticao_modelos', schema=None) as batch_op:
        # Adicionar google_doc_id como nullable inicialmente
        batch_op.add_column(sa.Column('google_doc_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('atualizado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_placeholders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_personas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ultima_sincronizacao', sa.DateTime(), nullable=True))
        batch_op.alter_column('doc_template_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    
    # Popula google_doc_id com valores de doc_template_id onde disponível
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE peticao_modelos SET google_doc_id = doc_template_id WHERE doc_template_id IS NOT NULL"))
    
    # Agora torna google_doc_id NOT NULL
    with op.batch_alter_table('peticao_modelos', schema=None) as batch_op:
        batch_op.alter_column('google_doc_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peticao_modelos', schema=None) as batch_op:
        batch_op.alter_column('doc_template_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('ultima_sincronizacao')
        batch_op.drop_column('total_personas')
        batch_op.drop_column('total_placeholders')
        batch_op.drop_column('atualizado_em')
        batch_op.drop_column('google_doc_id')

    op.drop_table('persona_analises')
    op.drop_table('formulario_placeholders')
    # ### end Alembic commands ###
