"""Add categoria field to peticao_placeholders

Revision ID: c12345678901
Revises: af01c0adb1f5
Create Date: 2025-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12345678901'
down_revision = 'af01c0adb1f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar coluna categoria à tabela peticao_placeholders
    with op.batch_alter_table('peticao_placeholders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=32), nullable=False, server_default='outros'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peticao_placeholders', schema=None) as batch_op:
        batch_op.drop_column('categoria')
    # ### end Alembic commands ### 