"""Criação inicial de todas as tabelas a partir do estado atual dos modelos

Revision ID: fb0f47444d4a
Revises: 
Create Date: 2025-06-30 18:31:20.532813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0f47444d4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoridades_transito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('clientes_peticionador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_pessoa', sa.Enum('FISICA', 'JURIDICA', name='tipopessoaenum'), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('telefone_celular', sa.String(length=32), nullable=True),
    sa.Column('telefone_outro', sa.String(length=32), nullable=True),
    sa.Column('primeiro_nome', sa.String(length=64), nullable=True),
    sa.Column('sobrenome', sa.String(length=128), nullable=True),
    sa.Column('nome_completo', sa.String(length=192), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg_numero', sa.String(length=32), nullable=True),
    sa.Column('rg_orgao_emissor', sa.String(length=32), nullable=True),
    sa.Column('rg_uf_emissor', sa.String(length=2), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('nacionalidade', sa.String(length=32), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('profissao', sa.String(length=64), nullable=True),
    sa.Column('cnh_numero', sa.String(length=32), nullable=True),
    sa.Column('endereco_logradouro', sa.String(length=128), nullable=True),
    sa.Column('endereco_numero', sa.String(length=16), nullable=True),
    sa.Column('endereco_complemento', sa.String(length=64), nullable=True),
    sa.Column('endereco_bairro', sa.String(length=64), nullable=True),
    sa.Column('endereco_cidade', sa.String(length=64), nullable=True),
    sa.Column('endereco_estado', sa.String(length=2), nullable=True),
    sa.Column('endereco_cep', sa.String(length=16), nullable=True),
    sa.Column('razao_social', sa.String(length=128), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('representante_nome', sa.String(length=128), nullable=True),
    sa.Column('representante_cpf', sa.String(length=14), nullable=True),
    sa.Column('representante_rg_numero', sa.String(length=32), nullable=True),
    sa.Column('representante_rg_orgao_emissor', sa.String(length=32), nullable=True),
    sa.Column('representante_rg_uf_emissor', sa.String(length=2), nullable=True),
    sa.Column('representante_cargo', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_pessoa', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticao_modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('google_doc_id', sa.String(length=64), nullable=False),
    sa.Column('doc_template_id', sa.String(length=64), nullable=True),
    sa.Column('pasta_destino_id', sa.String(length=64), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('total_placeholders', sa.Integer(), nullable=True),
    sa.Column('total_personas', sa.Integer(), nullable=True),
    sa.Column('ultima_sincronizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('template_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users_peticionador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('formulario_placeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=128), nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('tipo_campo', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('placeholder_text', sa.String(length=200), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('opcoes_json', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['peticao_modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formularios_gerados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['peticao_modelos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('persona_analises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.String(length=64), nullable=False),
    sa.Column('personas_detectadas', sa.JSON(), nullable=True),
    sa.Column('patterns_detectados', sa.JSON(), nullable=True),
    sa.Column('total_placeholders', sa.Integer(), nullable=True),
    sa.Column('total_personas', sa.Integer(), nullable=True),
    sa.Column('sugestoes', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['peticao_modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticao_placeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=64), nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('tipo_campo', sa.String(length=20), nullable=False),
    sa.Column('label_form', sa.String(length=120), nullable=True),
    sa.Column('opcoes_json', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['peticao_modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticoes_geradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('google_id', sa.String(length=64), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes_peticionador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peticoes_geradas')
    op.drop_table('peticao_placeholders')
    op.drop_table('persona_analises')
    op.drop_table('formularios_gerados')
    op.drop_table('formulario_placeholders')
    op.drop_table('users_peticionador')
    op.drop_table('template_categories')
    op.drop_table('peticao_modelos')
    op.drop_table('document_templates')
    op.drop_table('clientes_peticionador')
    op.drop_table('autoridades_transito')
    # ### end Alembic commands ###
